package com.example.akundu.android_mysql_nodejs.network;

public enum API {
    EMP_NO, EMP_SALARY,EMP_DETAILS,COUNTRY,SERVER_STATUS,CAR,SHOW_ALL_CUSTOMER,
    SHOW_SELECTED_CUSTOMER_ORDER_DETAILS,
    EMP_DEPT,EMP_BY_DEPT,LOG_BOOK,
}
